# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Score_Dialog(object):
    def setupUi(self, Score_Dialog):
        Score_Dialog.setObjectName("Score_Dialog")
        Score_Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Score_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(Score_Dialog)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(Score_Dialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.score = QtWidgets.QLabel(Score_Dialog)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.score.setFont(font)
        self.score.setObjectName("score")
        self.verticalLayout.addWidget(self.score, 0, QtCore.Qt.AlignHCenter)
        self.detail = QtWidgets.QLabel(Score_Dialog)
        self.detail.setObjectName("detail")
        self.verticalLayout.addWidget(self.detail)
        self.widget = QtWidgets.QWidget(Score_Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_home = QtWidgets.QPushButton(self.widget)
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout.addWidget(self.btn_home)
        self.btn_detail = QtWidgets.QPushButton(self.widget)
        self.btn_detail.setObjectName("btn_detail")
        self.horizontalLayout.addWidget(self.btn_detail)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Score_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Score_Dialog)

    def retranslateUi(self, Score_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Score_Dialog.setWindowTitle(_translate("Score_Dialog", "Dialog"))
        self.name.setText(_translate("Score_Dialog", "Tên bài tập"))
        self.label_2.setText(_translate("Score_Dialog", "Điểm của bạn"))
        self.score.setText(_translate("Score_Dialog", "10/10"))
        self.detail.setText(_translate("Score_Dialog", "chi tiết"))
        self.btn_home.setText(_translate("Score_Dialog", "Trang chủ"))
        self.btn_detail.setText(_translate("Score_Dialog", "Xem thống kê"))
